# Generated by Django 5.2.1 on 2025-05-30 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated date')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('token_type', models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh')], max_length=10)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklisted Token',
                'verbose_name_plural': 'Blacklisted Tokens',
            },
        ),
    ]
